services:

  worklex_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: worklex_backend

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "8000"

    volumes:
      - ./backend:/app

    working_dir: /app

    #-------------------------------------------------------------------------
    # Ajuste para evitar error por permisos con chmod
    #-------------------------------------------------------------------------
    #       python manage.py runserver 0.0.0.0:8000 &&

    command: >
      sh -c "
      python manage.py migrate --fake-initial &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "


    #command: >
    #  sh -c "
    #  ./wait-for-db.sh &&
    #  python manage.py migrate &&
    #  gunicorn config.wsgi:application --bind 0.0.0.0:8000
    #  "

    #depends_on:
    #  - frontend

    # Permite que otros contenedores esperen a que PostgreSQL esté listo.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/"]
      #test: ["CMD","curl","-f","http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - worklex_network



  worklex_frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: worklex_frontend

    restart: unless-stopped

    expose:
      - "5173"

    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

    working_dir: /app

    command: npm run dev -- --host 0.0.0.0

    # Permite que otros contenedores esperen a que PostgreSQL esté listo.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      #test: ["CMD","curl","-f","http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - worklex_network

  worklex_proxy:

    image: owasp/modsecurity-crs:nginx

    container_name: worklex_proxy

    depends_on:
      - worklex_backend
      - worklex_frontend

    networks:
      - worklex_network


networks:
  worklex_network:
    external: true
    #driver: bridge

volumes:
  frontend_node_modules: