# Indica bajo qué usuario Linux se ejecutarán los procesos Worker de NGINX.
user nginx;

# Define cuántos procesos Worker crea NGINX (según cores, 8 CPu = 8 Cores)
worker_processes auto;

server_tokens off;

client_body_timeout 10s;
client_header_timeout 10s;
send_timeout 10s;

client_body_buffer_size 128k;

large_client_header_buffers 4 16k;

reset_timedout_connection on;

# Cantidad máxima de conexiones simultáneas por Worker (8 Workers x 4096 conexiones)
events {
    worker_connections 4096;
}

http {
    # mportante para WorkLex porque servirá: Audios, Videos e Imágenes
    include /etc/nginx/mime.types;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=addr:10m;

    # Activa transferencia directa desde disco a red. Menor CPU y Más velocidad. Ideal para: MP4, MP3, PDF, JPG. PNG
    sendfile on;

    # Agrupa paquetes TCP, Menos tráfico Mayor rendimiento.
    tcp_nopush on;

   # Envía datos inmediatamente. Mejor respuesta para: API Django, JWT, Login, Consultas
    tcp_nodelay on;

   # Mantiene conexiones abiertas: 65 segundos (abre, reusa, reusa, reusa…cierra). Menos consumo Mayor velocidad.
    keepalive_timeout 65;

    # Tamaño máximo de archivos enviados.
    client_max_body_size 500M;

    # Oculta la versión de NGINX.
    server_tokens off;

    # Activa el algoritmo de compresión GZIP en NGINX. Dependiendo del contenido, la reducción puede ser del 60% al 90%
    gzip on;

    # Nivel de compresión.
    gzip_comp_level 6;

    # Solo comprime archivos mayores a 1 KB
    gzip_min_length 1024;

    # Permite que proxies y navegadores gestionen correctamente contenido comprimido y no comprimido.
    gzip_vary on;

    # También comprime respuestas cuando NGINX actúa como reverse proxy frente a Django.
    gzip_proxied any;

    # Indica qué tipos de archivos deben comprimirse.
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        application/xml+rss
        application/xhtml+xml
        image/svg+xml;

    # Carga todos los archivos de configuración
    include /etc/nginx/conf.d/*.conf;
}
