# Generated by Django 5.2.13 on 2026-05-21 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('CC', 'Cédula'), ('CE', 'Cédula Extranjería'), ('TI', 'Tarjeta Identidad'), ('PS', 'Pasaporte'), ('OT', 'Otro')], max_length=5)),
                ('doc_num', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"WorkLex"."PERSONS"',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"WorkLex"."SUBJECTS"',
            },
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=50)),
                ('link_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"WorkLex"."ROLES_ACCESS"',
                'unique_together': {('role_id', 'link_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.CharField(choices=[('ADMIN', 'Admin'), ('APRENDIZ', 'Aprendiz'), ('MONITOR', 'Monitor'), ('INSTRUCTOR', 'Instructor')], max_length=50)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente Activar Cuenta'), ('EN_FORMACION', 'En formación'), ('CANCELADO', 'Cancelado'), ('TRASLADADO', 'Trasladado'), ('RETIRO', 'Retiro voluntario'), ('APLAZADO', 'Aplazado')], max_length=50)),
                ('mfa', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
            ],
            options={
                'db_table': '"WorkLex"."USERS"',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('level', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestria')], max_length=10)),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.user')),
            ],
            options={
                'db_table': '"WorkLex"."TESTRESULTS"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': '"WorkLex"."POSTS"',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': '"WorkLex"."USERS_LOGS"',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
            ],
            options={
                'db_table': '"WorkLex"."RANKING"',
                'unique_together': {('subject', 'word_id')},
            },
        ),
        migrations.CreateModel(
            name='DigitalDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=50)),
                ('definition', models.CharField(max_length=255)),
                ('synonyms', models.CharField(max_length=255)),
                ('audio', models.CharField(max_length=255)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
            ],
            options={
                'db_table': '"WorkLex"."DIGITAL_DICTIONARIES"',
                'unique_together': {('word_id', 'subject')},
            },
        ),
    ]
