# Generated by Django 5.2.13 on 2026-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='digitaldictionary',
            unique_together={('word_id', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('subject', 'word_id')},
        ),
        migrations.AlterUniqueTogether(
            name='roleaccess',
            unique_together={('role_id', 'link_id')},
        ),
    ]
