# Generated by Django 5.2.13 on 2026-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_testresult_options_alter_testresult_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
