# Generated by Django 5.2.13 on 2026-06-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_person_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='character',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
