# Generated by Django 5.2.13 on 2026-06-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_testresult_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='process',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
