# Generated by Django 6.0.5 on 2026-06-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_create_superadmin'),
        ('users', '0006_testresult_process'),
    ]

    operations = [
    ]
